/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizationstudy;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author xfurman
 */
public class Main extends javax.swing.JFrame {

    private int activeIndex;
    private Map<Integer, JPanel> panels;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        registerScreens();
        jPanel1.add(panels.get(activeIndex));
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void registerScreens() {
        panels = new HashMap<>();
        FirstScreen p0 = new FirstScreen();
        activeIndex = 0;
        panels.put(0, p0);
        SecondScreen p1 = new SecondScreen();
        panels.put(1, p1);
        ThirdScreen p2 = new ThirdScreen();
        panels.put(2, p2);
        FourthScreen p3 = new FourthScreen();
        panels.put(3, p3);
        FifthScreen p4 = new FifthScreen();
        panels.put(4, p4);
        SixthScreen p5 = new SixthScreen();
        panels.put(5, p5);
        SeventhScreen p6 = new SeventhScreen();
        panels.put(6, p6);
        EightScreen p7 = new  EightScreen();
        panels.put(7, p7);
        NinthScreen p8 = new  NinthScreen();
        panels.put(8, p8);
        TenthScreen p9 = new  TenthScreen();
        panels.put(9, p9);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Study");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("<< Zpět");
        jButton1.setMargin(new java.awt.Insets(20, 25, 20, 25));
        jButton1.setMaximumSize(new java.awt.Dimension(107, 51));
        jButton1.setPreferredSize(new java.awt.Dimension(700, 450));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new java.awt.GridBagConstraints());
        jButton1.setVisible(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Další >>");
        jButton2.setMargin(new java.awt.Insets(20, 25, 20, 25));
        jButton2.setMaximumSize(new java.awt.Dimension(105, 51));
        jButton2.setPreferredSize(new java.awt.Dimension(700, 450));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new java.awt.GridBagConstraints());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (panels.get(activeIndex) instanceof FifthScreen) {
            if (!((FifthScreen) panels.get(activeIndex)).back()) {
                previousPanel();
            }
        }else if (panels.get(activeIndex) instanceof SeventhScreen) {
            if (!((SeventhScreen) panels.get(activeIndex)).back()) {
                previousPanel();
            }
        }else if (panels.get(activeIndex) instanceof NinthScreen) {
            if (!((NinthScreen) panels.get(activeIndex)).back()) {
                previousPanel();
            }
        }else{
            previousPanel();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (panels.get(activeIndex) instanceof SecondScreen) {
            if (((SecondScreen) panels.get(activeIndex)).validateForm()) {
                nextPanel();
            }
        } else if (panels.get(activeIndex) instanceof FifthScreen) {
            if (!((FifthScreen) panels.get(activeIndex)).next()) {
                nextPanel();
            }
        } else if (panels.get(activeIndex) instanceof SeventhScreen) {
            if (!((SeventhScreen) panels.get(activeIndex)).next()) {
                nextPanel();
            }
        }else if (panels.get(activeIndex) instanceof NinthScreen) {
            if (!((NinthScreen) panels.get(activeIndex)).next()) {
                nextPanel();
            }
        }else if (panels.get(activeIndex) instanceof TenthScreen) {
            save();
            System.exit(0);
        }else {
            nextPanel();
        }


    }//GEN-LAST:event_jButton2ActionPerformed
    private void previousPanel() {
        activeIndex--;
        jPanel1.removeAll();
        if (panels.containsKey(activeIndex)) {
            jPanel1.add(panels.get(activeIndex));
            jPanel1.revalidate();
            jPanel1.repaint();
        }
        jButton2.setVisible(true);
        if (!panels.containsKey(activeIndex - 1)) {
            jButton1.setVisible(false);
        }
        jButton2.setText("Další >>");
    }

    private void nextPanel() {
        activeIndex++;
        jPanel1.removeAll();
        if (panels.containsKey(activeIndex)) {
            jPanel1.add(panels.get(activeIndex));
            jPanel1.revalidate();
            jPanel1.repaint();
        }
        jButton1.setVisible(true);
        if (!panels.containsKey(activeIndex + 1)) {
            jButton2.setText("Uložit a ukončit");//setVisible(false);
        }
    }
    
    private void save(){
        String results = "";
         results +=((SecondScreen)panels.get(1)).getData();
         results +="Ukol 1\n";
         for(int i= 0; i<((FifthScreen)panels.get(4)).getAnswers().length; i++){
             results += (i+1) + (((FifthScreen)panels.get(4)).getAnswers()[i]==1?". stejny jedinec":". ruzne osoby") +"\n";
         }
         results +="Ukol 2\n";
         
         results +="Ukol 3\n";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
