/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizationstudy;

/**
 *
 * @author xfurman
 */
public class ThirdScreen extends javax.swing.JPanel {

    /**
     * Creates new form ThirdScreen
     */
    public ThirdScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(828, 600));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html>V následujících úkolech se na vaší obrazovce objeví 3 až 9 snímků obličeje člověka, na kterých jsou různými  způsoby  zobrazeny  rozdíly  mezi  dvěma  srovnávanými  trojrozměrnými  modely  obličeje. Každá 3D vizualizace je zobrazena z předního pohledu a z poloprofilu. <br> <br>Typy vizualizací:</html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("<html><b>Barevné mapy</b><br>Přiřazují vzdálenostem mezi obličeji barvy zvoleného arevného spektra, 3 rozdílné barevné palety byly vybrány:<br> <b>Gradient</b> – vzdálenosti (tj. rozdíly) mezi obličeji rostou s intenzitou modré barvy<br><b>Dva protichůdné gradienty</b> –  rozdíly mezi obličeji nejdříve rostou s úbytkem intenzity světlé barvy a poté stoupají s intenzitou tmavé barvy<br> <b>Spektrum</b> – rozdíly jsou zobrazeny barvami světelného spektra, kde je minimálním rozdílům přiřazena fialová barva a maximálním rozdílům barva červená<br> <br> <b>Transparence  se  simulací mlhy</b><br> Zobrazuje dva zarovnané obličeje, jejichž průhlednost je nastavena na hodnotu 50%. Volný prostor mezi modely je zbarvený červenou “mlhou”. Intenzita mlhy naznačuje velikost rozdílů.<br> <br> <b>Superpozice s konturami</b><br> Zobrazuje dva zarovnané obličeje, jejichž okraje překryvu jsou zvýrazněny konturami.<br> <br> <b>Transparence s glyfy</b><br> Zobrazuje dva zarovnané obličeje, jejichž průhlednost je nastavena na hodnotu 20%. Vnější (přední) model je opatřen pravidelně rozmístěnými značkami v podobě křížů (glyfy), které vrhají stíny na povrch zadního modelu. Míra deformace odpovídá rozdílům v místě glyfu.<br> <br> <b>Řezy</b><br> Zobrazují rozdíly mezi obličeji na řezech vedených ve třech základních tělních rovinách. </html>");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(770, 550));
        jScrollPane1.setViewportView(jLabel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
